Land Use and Vegetation Suitability pyBRAT symbology
Riverscapes/RiverscapesXML pull request #425
Opened 2021-12-12 02:26 UTC by Cashe93

Tracked in #395

2021-12-13 17:15 UTC, MattReimer approved these changes
This looks good to me. 

@Cashe93 let me know if this fixes things for qrave. I think I'll wait to rebuild webRAVE tiles for pyBRAT until we have the missing file issue sorted out.

2021-12-13 17:18 UTC, MattReimer requested changes
Hmmm. I can't merge this because of an automated check failing

```
E       [./Symbology/web/pyBRAT/py_VEG_CODE.txt] :: Error parsing QGIS Color Ramp: list index out of range
```

This file is missing the mandatory header

2021-12-14 23:04 UTC, jtgilbert requested changes
In the txt files for the web there are commas that need to be removed from the names. 
In py_lu.txt 'Not Developed' is 'Not,Developed'
In py_VEG_CODE.txt 'Barely Suitable' and 'Moderately Suitable' are have commas also ('Barely,Suitable' and 'Moderately,Suitable').
Do a find and replace to get rid of the unwanted commas.

2021-12-15 17:24 UTC, MattReimer requested changes
Just missing headers on one file

2021-12-15 17:24 UTC, MattReimer commented on Symbology/web/pyBRAT/py_VEG_CODE.txt
> +11,0,97,0,102,Preferred
No headers. This won't work

2021-12-15 21:24 UTC, Cashe93 commented
@MattReimer and @jtgilbert, I've just pushed commits with the requested changes.

2021-12-16 16:16 UTC, jtgilbert approved these changes

2021-12-16 16:58 UTC, Cashe93 commented
@MattReimer, it looks like the automated check has failed again. I've looked into it but can't figure out why. Let me know if this is something on my end and I'll get it fixed.

2021-12-16 17:00 UTC, MattReimer approved these changes

2021-12-16 17:28 UTC, MattReimer commented
@Cashe93 the line looks right to me. This could be a glitch in the checking software. I'll take it from here and integrate the branch when I'm done

2021-12-16 17:32 UTC, MattReimer commented
FOund the problem. You had a second set of header lines halfway down the file. Fixed and we can merge now.

2021-12-16 17:33 UTC, merged