BLM program added
Riverscapes/RiverscapesXML pull request #56
Opened 2021-05-14 21:11 UTC by MattReimer

@philipbaileynar please review this carefully. Kind of hard to change when it's done.

2021-05-14 21:12 UTC, MattReimer commented on Programs/blm/Program.xml
> +    <Meta name="access">PUBLIC</Meta>
Cool to be public?

2021-05-14 21:12 UTC, MattReimer commented on Programs/blm/Program.xml
> +  <MachineName>BLM</MachineName>
name and machine name oK?

2021-05-14 21:12 UTC, MattReimer commented on Programs/blm/Program.xml
> +      <Collection id="COL_HUC8" name="HUC8">
We're still on the HUC8 system right?

2021-05-14 21:13 UTC, MattReimer commented on Programs/blm/Program.xml
> +      <Product id="RSContext" name="Riverscapes Context (HUC8)" folder="RSContext" url="" />
The net_att program was RSContext only. Do we need more products allowed?

2021-05-14 21:16 UTC, philipbaileynar requested changes
Joe requested that the program be called "BLM Montana & Dakotas"

2021-05-14 23:37 UTC, MattReimer commented on Programs/blm/Program.xml
> +  <MachineName>BLM</MachineName>
BLM is good

2021-05-14 23:37 UTC, MattReimer commented on Programs/blm/Program.xml
> +    <Meta name="access">PUBLIC</Meta>
PRIVATE

2021-05-14 23:38 UTC, MattReimer commented on Programs/blm/Program.xml
> +      <Collection id="COL_HUC8" name="HUC8">
yes

2021-05-14 23:41 UTC, MattReimer commented on Programs/blm/Program.xml
> +      <Product id="RSContext" name="Riverscapes Context (HUC8)" folder="RSContext" url="" />
VBET, pyBRAT, BRAT, RVD, confinement

2021-05-14 23:59 UTC, merged

2021-05-18 15:53 UTC, joewheaton commented
Can I get access @philipbaileynar please?

2021-05-18 16:03 UTC, MattReimer commented
@joewheaton you have access now