symbolized land ownership for Q
Riverscapes/RiverscapesXML pull request #70
Opened 2021-05-18 20:44 UTC by lauren-herbine

Land ownership should be symbolized the same as Arc (aside from transparency) now. I also added USACE symbology, which isn't currently in Arc

2021-05-18 22:40 UTC, lauren-herbine commented
Should look like this:
![image](https://user-images.githubusercontent.com/73319684/118732537-c54e9a00-b7f7-11eb-8080-c2c3e5a47ae6.png)

2021-05-20 17:41 UTC, shelbysawyer approved these changes

2021-05-21 01:28 UTC, joewheaton commented on Symbology/qgis/RSContext/ownership.qml
> +      <category label="State" value="ST" symbol="8" render="true"/>
@lauren-herbine can you control the display order in the legend of these? If so, is it simply by changing this `symbol` key? Perhaps we should make the order in the legend a little clearer?

2021-05-21 01:30 UTC, joewheaton requested changes
Please see my minor changes suggested on display order to match what we do in Arc?

![image](https://user-images.githubusercontent.com/9723905/119068622-c6bbc600-b9a1-11eb-96a2-3e2cdfae54f0.png)

2021-06-02 23:09 UTC, lauren-herbine commented
@joewheaton I've played around with the .qml file a bit, and so far neither changing the symbol nor changing the actual order seems to have an affect on the order in the legend:

```
  <renderer-v2 enableorderby="0" type="categorizedSymbol" symbollevels="0" forceraster="0" attr="ADMIN_AGEN">
    <categories>
      <category label="Private" value="PVT" symbol="1" render="true"/>
      <category label="National Park Service" value="NPS" symbol="2" render="true"/>
      <category label="Fish and Wildlife Service" value="FWS" symbol="3" render="true"/>
      <category label="US Forest Service" value="USFS" symbol="4" render="true"/>
      <category label="Other" value="UND" symbol="5" render="true"/>
      <category label="State" value="ST" symbol="6" render="true"/>
      <category label="Bureau of Land Management" value="BLM" symbol="7" render="true"/>
      <category label="Bureau of Indian Affairs" value="BIA" symbol="8" render="true"/>
      <category label="US Army Corps of Engineers" value="USACE" symbol="9" render="true"/>
    </categories>
```

I'll do some research. @shelbysawyer tagging for future reference

2021-06-25 21:03 UTC, joewheaton approved these changes

2021-06-28 03:20 UTC, merged