VBET Evidence, Normalized, & Combined Evidence Symbology
Riverscapes/RiverscapesXML pull request #93
Opened 2021-05-27 00:09 UTC by shelbysawyer

This includes symbology key and .lyr file additions for VBET.

2021-06-26 02:37 UTC, joewheaton commented on RaveBusinessLogic/VBET.xml
>              </Children>
Does this collide with or conflict with other vbet_symbology business logic pull request (#118)  I just approved? Please avoid putting pull requests in simultaneously on different branches that make changes to same files.

2021-06-26 02:40 UTC, joewheaton requested changes
I am not going to review these binary files by downloading them. Please provide me screen shots of what each layer file is going to look like. They can just be a comment in pull request. Maybe sperate them using the `## Normalized Channel Layer` notation for headings to make it easy to see. Thanks! Also, I am thinking that the businessLogic.xml commit will collide with your other pull request.

2021-07-20 16:16 UTC, MattReimer commented
@shelbysawyer what's the status here? Last activity was 23 days ago.

2021-07-21 15:51 UTC, shelbysawyer commented
@MattReimer Sorry for the delay. I've been out of office since 7/12 and am getting caught up on everything today. I'll get this closed by end of week.

2021-07-21 16:19 UTC, MattReimer commented
> @MattReimer Sorry for the delay. I've been out of office since 7/12 and am getting caught up on everything today. I'll get this closed by end of week.

No worries and no rush. I'm just trying to figure out if any issues are stale. Sometimes github issues fall through the cracks.

2021-07-23 18:05 UTC, joewheaton commented
@MattReimer I suspect @shelbysawyer will get back to this as soon as we have first round of transform curves off her plate.

2021-08-11 17:05 UTC, closed without merging

2021-08-11 20:49 UTC, MattReimer commented
@shelby I noticed this got closed but it was never merged. Are you giving up on these changes?